2024-06-14 11:31:55,676 INFO django.utils.autoreload Watching for file changes with StatReloader
2024-06-14 11:32:04,158 INFO django.utils.autoreload C:\Users\maxiw\Desktop\netology-cloud-storage-master\storage\viewsets.py changed, reloading.
2024-06-14 11:32:04,462 INFO django.utils.autoreload Watching for file changes with StatReloader
2024-06-14 11:32:09,077 INFO django.utils.autoreload Watching for file changes with StatReloader
2024-06-14 11:32:12,727 WARNING django.request Not Found: /
2024-06-14 11:32:12,728 WARNING django.server "GET / HTTP/1.1" 404 2928
2024-06-14 11:32:12,794 WARNING django.request Not Found: /favicon.ico
2024-06-14 11:32:12,795 WARNING django.server "GET /favicon.ico HTTP/1.1" 404 2979
2024-06-14 11:32:36,750 INFO django.server "POST /login/ HTTP/1.1" 200 149
2024-06-14 11:32:36,788 INFO django.server "GET /api/files/ HTTP/1.1" 200 2
2024-06-14 11:32:36,792 INFO django.server "GET /api/users/6/ HTTP/1.1" 200 118
2024-06-14 11:32:36,796 INFO django.server "GET /api/users/ HTTP/1.1" 200 700
2024-06-14 11:32:36,813 INFO django.server "GET /api/users/6/ HTTP/1.1" 200 118
2024-06-14 11:32:36,822 INFO django.server "GET /api/files/ HTTP/1.1" 200 2
2024-06-14 11:32:36,841 INFO django.server "GET /api/users/ HTTP/1.1" 200 700
2024-06-14 11:33:05,411 INFO django.server "POST /api/files/ HTTP/1.1" 201 261
2024-06-14 11:33:05,443 INFO django.server "GET /api/files/ HTTP/1.1" 200 263
2024-06-14 11:33:26,474 WARNING django.request Bad Request: /api/files/
2024-06-14 11:33:26,474 WARNING django.server "POST /api/files/ HTTP/1.1" 400 41
2024-06-14 11:33:26,503 INFO django.server "GET /api/files/ HTTP/1.1" 200 263
2024-06-14 11:33:33,252 INFO django.server "GET /logout/ HTTP/1.1" 200 79
2024-06-14 11:33:37,578 ERROR django.request Internal Server Error: /login/
Traceback (most recent call last):
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\accounts\views.py", line 48, in login_view
    token = Token.objects.get(user=authenticated_user)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\django\db\models\query.py", line 647, in get
    raise self.model.DoesNotExist(
rest_framework.authtoken.models.Token.DoesNotExist: Token matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.NotNullViolation: null value in column "user_id" of relation "authtoken_token" violates not-null constraint
DETAIL:  Failing row contains (95e732947c08fbe8933b6c69c4ccd4fadf30af60, 2024-06-14 08:33:37.557664+00, null).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\accounts\views.py", line 50, in login_view
    token = Token.objects.create(user=authenticated_user)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\django\db\models\query.py", line 677, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\rest_framework\authtoken\models.py", line 33, in save
    return super().save(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\django\db\models\base.py", line 901, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\django\db\models\base.py", line 1059, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\django\db\models\base.py", line 1100, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\django\db\models\query.py", line 1845, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: null value in column "user_id" of relation "authtoken_token" violates not-null constraint
DETAIL:  Failing row contains (95e732947c08fbe8933b6c69c4ccd4fadf30af60, 2024-06-14 08:33:37.557664+00, null).

2024-06-14 11:33:37,582 ERROR django.server "POST /login/ HTTP/1.1" 500 201939
2024-06-14 11:33:42,677 INFO django.server "POST /register/ HTTP/1.1" 201 135
2024-06-14 11:33:42,695 INFO django.server "OPTIONS /api/users/7/ HTTP/1.1" 200 0
2024-06-14 11:33:42,698 INFO django.server "OPTIONS /api/users/7/ HTTP/1.1" 200 0
2024-06-14 11:33:42,716 INFO django.server "GET /api/files/ HTTP/1.1" 200 2
2024-06-14 11:33:42,720 INFO django.server "GET /api/users/7/ HTTP/1.1" 200 37
2024-06-14 11:33:42,727 INFO django.server "GET /api/users/ HTTP/1.1" 200 39
2024-06-14 11:33:42,743 INFO django.server "GET /api/users/7/ HTTP/1.1" 200 37
2024-06-14 11:33:42,750 INFO django.server "GET /api/users/ HTTP/1.1" 200 39
2024-06-14 11:33:42,757 INFO django.server "GET /api/files/ HTTP/1.1" 200 2
2024-06-14 11:33:54,574 INFO django.server "POST /api/files/ HTTP/1.1" 201 257
2024-06-14 11:33:54,606 INFO django.server "GET /api/files/ HTTP/1.1" 200 259
2024-06-14 11:33:59,035 INFO django.server "OPTIONS /api/files/2/ HTTP/1.1" 200 0
2024-06-14 11:33:59,060 INFO django.server "PATCH /api/files/2/ HTTP/1.1" 200 72
2024-06-14 11:33:59,089 INFO django.server "GET /api/files/ HTTP/1.1" 200 261
2024-06-14 11:34:00,108 INFO django.server "OPTIONS /api/files/2 HTTP/1.1" 200 0
2024-06-14 11:34:00,116 INFO django.server "GET /api/files/2 HTTP/1.1" 301 0
2024-06-14 11:34:00,118 INFO django.server "OPTIONS /api/files/2/ HTTP/1.1" 200 0
2024-06-14 11:34:00,136 INFO django.server "GET /api/files/2/ HTTP/1.1" 200 259
2024-06-14 11:34:00,183 INFO django.server "GET /files/test/weaqea.jpg HTTP/1.1" 200 67866
2024-06-14 11:34:12,469 INFO django.server "GET /s/file-5978263204388066456 HTTP/1.1" 301 0
2024-06-14 11:34:12,488 WARNING django.request Not Found: /s/file-5978263204388066456/
2024-06-14 11:34:12,489 WARNING django.server "GET /s/file-5978263204388066456/ HTTP/1.1" 404 20
2024-06-14 11:34:21,181 WARNING django.request Not Found: /s/file-5978263204388066456/
2024-06-14 11:34:21,181 WARNING django.server "GET /s/file-5978263204388066456/ HTTP/1.1" 404 20
2024-06-14 11:34:43,269 INFO django.server "GET /logout/ HTTP/1.1" 200 67
2024-06-14 11:34:50,398 INFO django.server "POST /login/ HTTP/1.1" 200 149
2024-06-14 11:34:50,445 INFO django.server "GET /api/users/6/ HTTP/1.1" 200 128
2024-06-14 11:34:50,445 INFO django.server "GET /api/files/ HTTP/1.1" 200 523
2024-06-14 11:34:50,449 INFO django.server "GET /api/users/ HTTP/1.1" 200 836
2024-06-14 11:34:50,472 INFO django.server "GET /api/files/ HTTP/1.1" 200 523
2024-06-14 11:34:50,473 INFO django.server "GET /api/users/6/ HTTP/1.1" 200 128
2024-06-14 11:34:50,481 INFO django.server "GET /api/users/ HTTP/1.1" 200 836
2024-06-14 11:34:52,586 INFO django.server "GET /api/users/6/ HTTP/1.1" 200 128
2024-06-14 11:34:52,605 INFO django.server "GET /api/users/6/ HTTP/1.1" 200 128
2024-06-14 11:34:52,627 INFO django.server "GET /api/users/6/ HTTP/1.1" 200 128
2024-06-14 11:34:52,646 INFO django.server "GET /api/users/6/ HTTP/1.1" 200 128
2024-06-14 11:34:52,655 INFO django.server "GET /api/users/ HTTP/1.1" 200 836
2024-06-14 11:34:52,677 INFO django.server "GET /api/users/ HTTP/1.1" 200 836
2024-06-14 11:34:54,635 INFO django.server "DELETE /api/users/2/ HTTP/1.1" 204 54
2024-06-14 11:34:54,640 INFO django.server - Broken pipe from ('127.0.0.1', 58871)
2024-06-14 11:34:54,656 INFO django.server "GET /api/users/ HTTP/1.1" 200 720
2024-06-14 11:34:56,198 INFO django.server "DELETE /api/users/3/ HTTP/1.1" 204 53
2024-06-14 11:34:56,200 INFO django.server - Broken pipe from ('127.0.0.1', 58842)
2024-06-14 11:34:56,220 INFO django.server "GET /api/users/ HTTP/1.1" 200 605
2024-06-14 11:34:57,372 INFO django.server "DELETE /api/users/4/ HTTP/1.1" 204 58
2024-06-14 11:34:57,375 INFO django.server - Broken pipe from ('127.0.0.1', 58932)
2024-06-14 11:34:57,392 INFO django.server "GET /api/users/ HTTP/1.1" 200 485
2024-06-14 11:34:58,546 INFO django.server "DELETE /api/users/5/ HTTP/1.1" 204 54
2024-06-14 11:34:58,548 INFO django.server - Broken pipe from ('127.0.0.1', 58935)
2024-06-14 11:34:58,568 INFO django.server "GET /api/users/ HTTP/1.1" 200 369
2024-06-14 11:35:00,783 INFO django.server "PATCH /api/users/7/ HTTP/1.1" 200 52
2024-06-14 11:35:00,808 INFO django.server "GET /api/users/ HTTP/1.1" 200 368
2024-06-14 11:35:02,192 INFO django.server "DELETE /api/users/7/ HTTP/1.1" 204 52
2024-06-14 11:35:02,194 INFO django.server - Broken pipe from ('127.0.0.1', 58940)
2024-06-14 11:35:02,213 INFO django.server "GET /api/users/ HTTP/1.1" 200 243
2024-06-14 11:45:03,043 INFO django.utils.autoreload Watching for file changes with StatReloader
2024-06-14 12:28:29,509 INFO django.utils.autoreload Watching for file changes with StatReloader
2024-06-14 12:30:06,539 INFO django.utils.autoreload Watching for file changes with StatReloader
2024-06-14 12:33:32,273 INFO django.utils.autoreload Watching for file changes with StatReloader
2024-06-14 12:35:17,610 INFO django.utils.autoreload C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\accounts\models.py changed, reloading.
2024-06-14 12:35:17,902 INFO django.utils.autoreload Watching for file changes with StatReloader
2024-06-14 12:35:20,413 INFO django.utils.autoreload Watching for file changes with StatReloader
2024-06-14 12:40:19,276 INFO django.utils.autoreload Watching for file changes with StatReloader
2024-06-14 12:43:11,690 INFO django.utils.autoreload Watching for file changes with StatReloader
2024-06-14 12:44:34,527 INFO django.utils.autoreload C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\server\settings.py changed, reloading.
2024-06-14 12:44:34,834 INFO django.utils.autoreload Watching for file changes with StatReloader
2024-06-14 12:44:36,111 INFO django.utils.autoreload Watching for file changes with StatReloader
2024-06-14 12:45:16,068 ERROR django.server "GET /admin/ HTTP/1.1" 500 59
2024-06-14 12:45:21,085 ERROR django.server "GET / HTTP/1.1" 500 59
2024-06-14 12:45:29,042 INFO django.utils.autoreload Watching for file changes with StatReloader
2024-06-14 12:45:31,962 ERROR django.server "GET / HTTP/1.1" 500 59
2024-06-14 12:47:32,143 INFO django.utils.autoreload C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\server\settings.py changed, reloading.
2024-06-14 12:47:32,506 INFO django.utils.autoreload Watching for file changes with StatReloader
2024-06-14 12:47:35,263 INFO django.utils.autoreload Watching for file changes with StatReloader
2024-06-14 12:47:38,876 ERROR django.server "GET / HTTP/1.1" 500 59
2024-06-14 12:47:52,021 ERROR django.server "GET / HTTP/1.1" 500 59
2024-06-14 12:47:52,134 INFO django.utils.autoreload C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\server\settings.py changed, reloading.
2024-06-14 12:47:52,496 INFO django.utils.autoreload Watching for file changes with StatReloader
2024-06-14 12:47:57,077 INFO django.utils.autoreload Watching for file changes with StatReloader
2024-06-14 12:48:10,407 INFO django.utils.autoreload Watching for file changes with StatReloader
2024-06-14 12:48:14,239 WARNING django.request Not Found: /
2024-06-14 12:48:14,240 WARNING django.server "GET / HTTP/1.1" 404 2932
2024-06-14 13:05:29,670 INFO django.utils.autoreload Watching for file changes with StatReloader
2024-06-14 13:06:01,988 INFO django.server "GET /admin/ HTTP/1.1" 302 0
2024-06-14 13:06:02,002 INFO django.server "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4158
2024-06-14 13:06:02,018 INFO django.server "GET /static/admin/css/base.css HTTP/1.1" 304 0
2024-06-14 13:06:02,023 INFO django.server "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
2024-06-14 13:06:02,027 INFO django.server "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
2024-06-14 13:06:02,031 INFO django.server "GET /static/admin/css/login.css HTTP/1.1" 304 0
2024-06-14 13:06:02,037 INFO django.server "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
2024-06-14 13:06:02,040 INFO django.server "GET /static/admin/js/theme.js HTTP/1.1" 304 0
2024-06-14 13:06:02,043 INFO django.server "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
2024-06-14 13:06:10,089 INFO django.server "POST /admin/login/?next=/admin/ HTTP/1.1" 200 4319
2024-06-14 13:09:17,569 INFO django.utils.autoreload Watching for file changes with StatReloader
2024-06-14 13:09:21,844 INFO django.server "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
2024-06-14 13:09:21,876 INFO django.server "GET /admin/ HTTP/1.1" 200 6471
2024-06-14 13:09:56,822 INFO django.utils.autoreload C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\server\settings.py changed, reloading.
2024-06-14 13:09:57,159 INFO django.utils.autoreload Watching for file changes with StatReloader
2024-06-14 13:09:59,094 INFO django.utils.autoreload Watching for file changes with StatReloader
2024-06-14 13:10:45,971 INFO django.utils.autoreload C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\server\settings.py changed, reloading.
2024-06-14 13:10:46,287 INFO django.utils.autoreload Watching for file changes with StatReloader
2024-06-14 13:10:54,840 INFO django.utils.autoreload C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\server\settings.py changed, reloading.
2024-06-14 13:10:56,304 INFO django.utils.autoreload Watching for file changes with StatReloader
2024-06-14 13:11:10,979 INFO django.utils.autoreload Watching for file changes with StatReloader
2024-06-14 13:11:14,602 INFO django.server "GET /admin/ HTTP/1.1" 200 6471
2024-06-14 13:11:41,665 INFO django.utils.autoreload Watching for file changes with StatReloader
2024-06-14 13:12:59,722 INFO django.server "GET /admin/ HTTP/1.1" 200 6471
2024-06-14 13:13:01,827 INFO django.server "GET /admin/accounts/ HTTP/1.1" 200 5072
2024-06-14 13:13:03,085 INFO django.server "GET /admin/ HTTP/1.1" 200 6471
2024-06-14 13:13:03,768 INFO django.server "GET /admin/authtoken/ HTTP/1.1" 200 5089
2024-06-14 13:13:04,585 INFO django.server "GET /admin/ HTTP/1.1" 200 6471
2024-06-14 13:13:05,238 INFO django.server "GET /admin/storage/ HTTP/1.1" 200 5057
2024-06-14 13:13:05,922 INFO django.server "GET /admin/ HTTP/1.1" 200 6471
2024-06-14 13:13:06,726 INFO django.server "GET /admin/accounts/ HTTP/1.1" 200 5072
2024-06-14 13:13:08,286 INFO django.server "GET /admin/accounts/customuser/add/ HTTP/1.1" 200 14907
2024-06-14 13:13:08,389 INFO django.server "GET /static/admin/css/forms.css HTTP/1.1" 200 9048
2024-06-14 13:13:08,392 INFO django.server "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
2024-06-14 13:13:08,393 INFO django.server "GET /static/admin/js/inlines.js HTTP/1.1" 200 15526
2024-06-14 13:13:08,397 INFO django.server "GET /static/admin/css/widgets.css HTTP/1.1" 200 11800
2024-06-14 13:13:08,404 INFO django.server "GET /static/admin/js/change_form.js HTTP/1.1" 200 606
2024-06-14 13:13:08,414 INFO django.server "GET /admin/jsi18n/ HTTP/1.1" 200 3342
2024-06-14 13:13:14,905 INFO django.server "GET /admin/storage/document/ HTTP/1.1" 200 7707
2024-06-14 13:13:14,923 INFO django.server "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
2024-06-14 13:13:14,923 INFO django.server "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
2024-06-14 13:13:14,924 INFO django.server "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
2024-06-14 13:13:14,929 INFO django.server "GET /static/admin/js/core.js HTTP/1.1" 304 0
2024-06-14 13:13:14,929 INFO django.server "GET /static/admin/js/actions.js HTTP/1.1" 304 0
2024-06-14 13:13:14,929 INFO django.server "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
2024-06-14 13:13:14,935 INFO django.server "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
2024-06-14 13:13:14,935 INFO django.server "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
2024-06-14 13:13:14,935 INFO django.server "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
2024-06-14 13:13:14,939 INFO django.server "GET /static/admin/js/filters.js HTTP/1.1" 304 0
2024-06-14 13:13:14,952 INFO django.server "GET /admin/jsi18n/ HTTP/1.1" 200 3342
2024-06-14 13:13:14,963 INFO django.server "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
2024-06-14 13:13:16,079 INFO django.server "GET /admin/authtoken/tokenproxy/ HTTP/1.1" 200 7659
2024-06-14 13:13:16,709 INFO django.server "GET /admin/accounts/customuser/ HTTP/1.1" 200 10391
2024-06-14 13:13:16,727 INFO django.server "GET /static/admin/img/search.svg HTTP/1.1" 304 0
2024-06-14 13:13:16,727 INFO django.server "GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0
2024-06-14 13:13:16,746 INFO django.server "GET /admin/jsi18n/ HTTP/1.1" 200 3342
2024-06-14 13:13:16,759 INFO django.server "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 304 0
2024-06-14 13:13:20,168 INFO django.server "GET /admin/ HTTP/1.1" 200 6471
2024-06-14 13:13:20,184 INFO django.server "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
2024-06-14 13:18:22,758 INFO django.utils.autoreload C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\server\settings.py changed, reloading.
2024-06-14 13:18:23,125 INFO django.utils.autoreload Watching for file changes with StatReloader
2024-06-14 13:26:42,581 INFO django.utils.autoreload Watching for file changes with StatReloader
2024-06-14 13:48:28,395 INFO django.server "OPTIONS /register/ HTTP/1.1" 200 0
2024-06-14 13:48:28,665 INFO django.server "POST /register/ HTTP/1.1" 201 133
2024-06-14 13:48:28,682 INFO django.server "OPTIONS /api/files/ HTTP/1.1" 200 0
2024-06-14 13:48:28,682 INFO django.server "OPTIONS /api/users/2/ HTTP/1.1" 200 0
2024-06-14 13:48:28,684 INFO django.server "OPTIONS /api/users/ HTTP/1.1" 200 0
2024-06-14 13:48:28,685 INFO django.server "OPTIONS /api/users/2/ HTTP/1.1" 200 0
2024-06-14 13:48:28,687 INFO django.server "OPTIONS /api/files/ HTTP/1.1" 200 0
2024-06-14 13:48:28,690 INFO django.server "OPTIONS /api/users/ HTTP/1.1" 200 0
2024-06-14 13:48:28,697 WARNING django.request Not Found: /api/files/
2024-06-14 13:48:28,697 WARNING django.server "GET /api/files/ HTTP/1.1" 404 4915
2024-06-14 13:48:28,706 WARNING django.request Not Found: /api/files/
2024-06-14 13:48:28,706 WARNING django.server "GET /api/files/ HTTP/1.1" 404 4915
2024-06-14 13:48:28,732 ERROR django.request Internal Server Error: /api/users/2/
Traceback (most recent call last):
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\mixins.py", line 56, in retrieve
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 555, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\fields.py", line 1838, in to_representation
    return method(value)
           ^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\accounts\serializers.py", line 51, in get_documents
    user_documents = Document.objects.filter(by_user=obj)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1600, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1632, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1482, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1294, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'by_user' into field. Choices are: description, file, filename, id, share_link, size, upload_datetime, uploaded_by, uploaded_by_id
2024-06-14 13:48:28,739 ERROR django.server "GET /api/users/2/ HTTP/1.1" 500 165292
2024-06-14 13:48:28,756 ERROR django.request Internal Server Error: /api/users/
Traceback (most recent call last):
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\fields.py", line 1838, in to_representation
    return method(value)
           ^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\accounts\serializers.py", line 51, in get_documents
    user_documents = Document.objects.filter(by_user=obj)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1600, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1632, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1482, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1294, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'by_user' into field. Choices are: description, file, filename, id, share_link, size, upload_datetime, uploaded_by, uploaded_by_id
2024-06-14 13:48:28,759 ERROR django.server "GET /api/users/ HTTP/1.1" 500 174357
2024-06-14 13:48:28,808 ERROR django.request Internal Server Error: /api/users/2/
Traceback (most recent call last):
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\mixins.py", line 56, in retrieve
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 555, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\fields.py", line 1838, in to_representation
    return method(value)
           ^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\accounts\serializers.py", line 51, in get_documents
    user_documents = Document.objects.filter(by_user=obj)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1600, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1632, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1482, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1294, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'by_user' into field. Choices are: description, file, filename, id, share_link, size, upload_datetime, uploaded_by, uploaded_by_id
2024-06-14 13:48:28,810 ERROR django.server "GET /api/users/2/ HTTP/1.1" 500 165292
2024-06-14 13:48:28,839 ERROR django.request Internal Server Error: /api/users/
Traceback (most recent call last):
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\fields.py", line 1838, in to_representation
    return method(value)
           ^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\accounts\serializers.py", line 51, in get_documents
    user_documents = Document.objects.filter(by_user=obj)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1600, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1632, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1482, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1294, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'by_user' into field. Choices are: description, file, filename, id, share_link, size, upload_datetime, uploaded_by, uploaded_by_id
2024-06-14 13:48:28,841 ERROR django.server "GET /api/users/ HTTP/1.1" 500 174357
2024-06-14 13:48:38,583 INFO django.server "OPTIONS /login/ HTTP/1.1" 200 0
2024-06-14 13:48:38,851 INFO django.server "POST /login/ HTTP/1.1" 200 135
2024-06-14 13:48:38,869 INFO django.server "OPTIONS /api/users/1/ HTTP/1.1" 200 0
2024-06-14 13:48:38,869 INFO django.server "OPTIONS /api/users/1/ HTTP/1.1" 200 0
2024-06-14 13:48:38,871 WARNING django.request Not Found: /api/files/
2024-06-14 13:48:38,872 WARNING django.server "GET /api/files/ HTTP/1.1" 404 4915
2024-06-14 13:48:38,881 WARNING django.request Not Found: /api/files/
2024-06-14 13:48:38,881 WARNING django.server "GET /api/files/ HTTP/1.1" 404 4915
2024-06-14 13:48:38,906 ERROR django.request Internal Server Error: /api/users/
Traceback (most recent call last):
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\fields.py", line 1838, in to_representation
    return method(value)
           ^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\accounts\serializers.py", line 38, in get_documents
    user_documents = Document.objects.filter(by_user=obj)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1600, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1632, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1482, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1294, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'by_user' into field. Choices are: description, file, filename, id, share_link, size, upload_datetime, uploaded_by, uploaded_by_id
2024-06-14 13:48:38,907 ERROR django.server "GET /api/users/ HTTP/1.1" 500 176540
2024-06-14 13:48:38,930 ERROR django.request Internal Server Error: /api/users/1/
Traceback (most recent call last):
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\mixins.py", line 56, in retrieve
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 555, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\fields.py", line 1838, in to_representation
    return method(value)
           ^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\accounts\serializers.py", line 38, in get_documents
    user_documents = Document.objects.filter(by_user=obj)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1600, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1632, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1482, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1294, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'by_user' into field. Choices are: description, file, filename, id, share_link, size, upload_datetime, uploaded_by, uploaded_by_id
2024-06-14 13:48:38,932 ERROR django.server "GET /api/users/1/ HTTP/1.1" 500 166794
2024-06-14 13:48:38,970 ERROR django.request Internal Server Error: /api/users/
Traceback (most recent call last):
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\fields.py", line 1838, in to_representation
    return method(value)
           ^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\accounts\serializers.py", line 38, in get_documents
    user_documents = Document.objects.filter(by_user=obj)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1600, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1632, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1482, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1294, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'by_user' into field. Choices are: description, file, filename, id, share_link, size, upload_datetime, uploaded_by, uploaded_by_id
2024-06-14 13:48:38,972 ERROR django.server "GET /api/users/ HTTP/1.1" 500 176540
2024-06-14 13:48:39,009 ERROR django.request Internal Server Error: /api/users/1/
Traceback (most recent call last):
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\mixins.py", line 56, in retrieve
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 555, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\fields.py", line 1838, in to_representation
    return method(value)
           ^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\accounts\serializers.py", line 38, in get_documents
    user_documents = Document.objects.filter(by_user=obj)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1600, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1632, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1482, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1294, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'by_user' into field. Choices are: description, file, filename, id, share_link, size, upload_datetime, uploaded_by, uploaded_by_id
2024-06-14 13:48:39,011 ERROR django.server "GET /api/users/1/ HTTP/1.1" 500 166794
2024-06-14 13:48:44,105 WARNING django.request Bad Request: /login/
2024-06-14 13:48:44,106 WARNING django.server "POST /login/ HTTP/1.1" 400 89
2024-06-14 13:48:50,331 WARNING django.request Bad Request: /register/
2024-06-14 13:48:50,332 WARNING django.server "POST /register/ HTTP/1.1" 400 125
2024-06-14 13:48:53,767 WARNING django.request Bad Request: /register/
2024-06-14 13:48:53,767 WARNING django.server "POST /register/ HTTP/1.1" 400 125
2024-06-14 13:48:55,435 INFO django.server "POST /register/ HTTP/1.1" 201 135
2024-06-14 13:48:55,450 INFO django.server "OPTIONS /api/users/3/ HTTP/1.1" 200 0
2024-06-14 13:48:55,452 INFO django.server "OPTIONS /api/users/3/ HTTP/1.1" 200 0
2024-06-14 13:48:55,458 WARNING django.request Not Found: /api/files/
2024-06-14 13:48:55,459 WARNING django.server "GET /api/files/ HTTP/1.1" 404 4915
2024-06-14 13:48:55,467 WARNING django.request Not Found: /api/files/
2024-06-14 13:48:55,468 WARNING django.server "GET /api/files/ HTTP/1.1" 404 4915
2024-06-14 13:48:55,494 ERROR django.request Internal Server Error: /api/users/3/
Traceback (most recent call last):
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\mixins.py", line 56, in retrieve
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 555, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\fields.py", line 1838, in to_representation
    return method(value)
           ^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\accounts\serializers.py", line 51, in get_documents
    user_documents = Document.objects.filter(by_user=obj)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1600, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1632, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1482, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1294, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'by_user' into field. Choices are: description, file, filename, id, share_link, size, upload_datetime, uploaded_by, uploaded_by_id
2024-06-14 13:48:55,499 ERROR django.server "GET /api/users/3/ HTTP/1.1" 500 165315
2024-06-14 13:48:55,515 ERROR django.request Internal Server Error: /api/users/
Traceback (most recent call last):
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\fields.py", line 1838, in to_representation
    return method(value)
           ^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\accounts\serializers.py", line 51, in get_documents
    user_documents = Document.objects.filter(by_user=obj)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1600, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1632, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1482, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1294, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'by_user' into field. Choices are: description, file, filename, id, share_link, size, upload_datetime, uploaded_by, uploaded_by_id
2024-06-14 13:48:55,518 ERROR django.server "GET /api/users/ HTTP/1.1" 500 174385
2024-06-14 13:48:55,555 ERROR django.request Internal Server Error: /api/users/3/
Traceback (most recent call last):
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\mixins.py", line 56, in retrieve
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 555, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\fields.py", line 1838, in to_representation
    return method(value)
           ^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\accounts\serializers.py", line 51, in get_documents
    user_documents = Document.objects.filter(by_user=obj)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1600, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1632, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1482, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1294, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'by_user' into field. Choices are: description, file, filename, id, share_link, size, upload_datetime, uploaded_by, uploaded_by_id
2024-06-14 13:48:55,559 ERROR django.server "GET /api/users/3/ HTTP/1.1" 500 165315
2024-06-14 13:48:55,579 ERROR django.request Internal Server Error: /api/users/
Traceback (most recent call last):
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\fields.py", line 1838, in to_representation
    return method(value)
           ^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\accounts\serializers.py", line 51, in get_documents
    user_documents = Document.objects.filter(by_user=obj)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1600, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1632, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1482, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1294, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'by_user' into field. Choices are: description, file, filename, id, share_link, size, upload_datetime, uploaded_by, uploaded_by_id
2024-06-14 13:48:55,581 ERROR django.server "GET /api/users/ HTTP/1.1" 500 174385
2024-06-14 13:49:18,893 INFO django.utils.autoreload Watching for file changes with StatReloader
2024-06-14 13:49:21,858 WARNING django.request Not Found: /api/files/
2024-06-14 13:49:21,858 WARNING django.server "GET /api/files/ HTTP/1.1" 404 4915
2024-06-14 13:49:21,865 WARNING django.request Not Found: /api/files/
2024-06-14 13:49:21,865 WARNING django.server "GET /api/files/ HTTP/1.1" 404 4915
2024-06-14 13:49:21,895 ERROR django.request Internal Server Error: /api/users/
Traceback (most recent call last):
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\fields.py", line 1838, in to_representation
    return method(value)
           ^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\accounts\serializers.py", line 51, in get_documents
    user_documents = Document.objects.filter(by_user=obj)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1600, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1632, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1482, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1294, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'by_user' into field. Choices are: description, file, filename, id, share_link, size, upload_datetime, uploaded_by, uploaded_by_id
2024-06-14 13:49:21,902 ERROR django.server "GET /api/users/ HTTP/1.1" 500 174385
2024-06-14 13:49:21,921 ERROR django.request Internal Server Error: /api/users/3/
Traceback (most recent call last):
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\mixins.py", line 56, in retrieve
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 555, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\fields.py", line 1838, in to_representation
    return method(value)
           ^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\accounts\serializers.py", line 51, in get_documents
    user_documents = Document.objects.filter(by_user=obj)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1600, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1632, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1482, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1294, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'by_user' into field. Choices are: description, file, filename, id, share_link, size, upload_datetime, uploaded_by, uploaded_by_id
2024-06-14 13:49:21,922 ERROR django.server "GET /api/users/3/ HTTP/1.1" 500 165315
2024-06-14 13:49:21,962 ERROR django.request Internal Server Error: /api/users/
Traceback (most recent call last):
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\fields.py", line 1838, in to_representation
    return method(value)
           ^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\accounts\serializers.py", line 51, in get_documents
    user_documents = Document.objects.filter(by_user=obj)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1600, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1632, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1482, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1294, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'by_user' into field. Choices are: description, file, filename, id, share_link, size, upload_datetime, uploaded_by, uploaded_by_id
2024-06-14 13:49:21,964 ERROR django.server "GET /api/users/ HTTP/1.1" 500 174385
2024-06-14 13:49:21,975 ERROR django.request Internal Server Error: /api/users/3/
Traceback (most recent call last):
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\mixins.py", line 56, in retrieve
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 555, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\fields.py", line 1838, in to_representation
    return method(value)
           ^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\accounts\serializers.py", line 51, in get_documents
    user_documents = Document.objects.filter(by_user=obj)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1600, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1632, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1482, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1294, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'by_user' into field. Choices are: description, file, filename, id, share_link, size, upload_datetime, uploaded_by, uploaded_by_id
2024-06-14 13:49:21,978 ERROR django.server "GET /api/users/3/ HTTP/1.1" 500 165315
2024-06-14 13:49:37,404 INFO django.utils.autoreload Watching for file changes with StatReloader
2024-06-14 13:49:42,222 INFO django.server "POST /register/ HTTP/1.1" 201 131
2024-06-14 13:49:42,238 INFO django.server "OPTIONS /api/users/4/ HTTP/1.1" 200 0
2024-06-14 13:49:42,243 INFO django.server "OPTIONS /api/users/4/ HTTP/1.1" 200 0
2024-06-14 13:49:42,248 WARNING django.request Not Found: /api/files/
2024-06-14 13:49:42,249 WARNING django.server "GET /api/files/ HTTP/1.1" 404 4915
2024-06-14 13:49:42,257 WARNING django.request Not Found: /api/files/
2024-06-14 13:49:42,258 WARNING django.server "GET /api/files/ HTTP/1.1" 404 4915
2024-06-14 13:49:42,304 ERROR django.request Internal Server Error: /api/users/
Traceback (most recent call last):
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\fields.py", line 1838, in to_representation
    return method(value)
           ^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\accounts\serializers.py", line 51, in get_documents
    user_documents = Document.objects.filter(by_user=obj)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1600, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1632, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1482, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1294, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'by_user' into field. Choices are: description, file, filename, id, share_link, size, upload_datetime, uploaded_by, uploaded_by_id
2024-06-14 13:49:42,306 ERROR django.request Internal Server Error: /api/users/4/
Traceback (most recent call last):
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\mixins.py", line 56, in retrieve
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 555, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\fields.py", line 1838, in to_representation
    return method(value)
           ^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\accounts\serializers.py", line 51, in get_documents
    user_documents = Document.objects.filter(by_user=obj)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1600, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1632, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1482, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1294, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'by_user' into field. Choices are: description, file, filename, id, share_link, size, upload_datetime, uploaded_by, uploaded_by_id
2024-06-14 13:49:42,308 ERROR django.server "GET /api/users/ HTTP/1.1" 500 174329
2024-06-14 13:49:42,309 ERROR django.server "GET /api/users/4/ HTTP/1.1" 500 165269
2024-06-14 13:49:42,361 ERROR django.request Internal Server Error: /api/users/4/
Traceback (most recent call last):
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\mixins.py", line 56, in retrieve
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 555, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\fields.py", line 1838, in to_representation
    return method(value)
           ^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\accounts\serializers.py", line 51, in get_documents
    user_documents = Document.objects.filter(by_user=obj)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1600, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1632, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1482, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1294, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'by_user' into field. Choices are: description, file, filename, id, share_link, size, upload_datetime, uploaded_by, uploaded_by_id
2024-06-14 13:49:42,363 ERROR django.server "GET /api/users/4/ HTTP/1.1" 500 165269
2024-06-14 13:49:42,375 ERROR django.request Internal Server Error: /api/users/
Traceback (most recent call last):
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\rest_framework\fields.py", line 1838, in to_representation
    return method(value)
           ^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\accounts\serializers.py", line 51, in get_documents
    user_documents = Document.objects.filter(by_user=obj)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1600, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1632, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1482, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1294, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'by_user' into field. Choices are: description, file, filename, id, share_link, size, upload_datetime, uploaded_by, uploaded_by_id
2024-06-14 13:49:42,377 ERROR django.server "GET /api/users/ HTTP/1.1" 500 174329
2024-06-14 13:50:47,995 INFO django.utils.autoreload C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\accounts\serializers.py changed, reloading.
2024-06-14 13:50:48,320 INFO django.utils.autoreload Watching for file changes with StatReloader
2024-06-14 13:50:50,097 INFO django.utils.autoreload Watching for file changes with StatReloader
2024-06-14 13:50:55,031 INFO django.server "POST /register/ HTTP/1.1" 201 147
2024-06-14 13:50:55,048 INFO django.server "OPTIONS /api/users/5/ HTTP/1.1" 200 0
2024-06-14 13:50:55,050 INFO django.server "OPTIONS /api/users/5/ HTTP/1.1" 200 0
2024-06-14 13:50:55,056 WARNING django.request Not Found: /api/files/
2024-06-14 13:50:55,056 WARNING django.server "GET /api/files/ HTTP/1.1" 404 4915
2024-06-14 13:50:55,065 WARNING django.request Not Found: /api/files/
2024-06-14 13:50:55,065 WARNING django.server "GET /api/files/ HTTP/1.1" 404 4915
2024-06-14 13:50:55,070 INFO django.server "GET /api/users/ HTTP/1.1" 200 51
2024-06-14 13:50:55,075 INFO django.server "GET /api/users/5/ HTTP/1.1" 200 49
2024-06-14 13:50:55,094 INFO django.server "GET /api/users/5/ HTTP/1.1" 200 49
2024-06-14 13:50:55,113 INFO django.server "GET /api/users/ HTTP/1.1" 200 51
2024-06-14 13:51:09,444 WARNING django.request Not Found: /api/files/
2024-06-14 13:51:09,451 WARNING django.server "POST /api/files/ HTTP/1.1" 404 4916
2024-06-14 13:51:09,469 WARNING django.request Not Found: /api/files/
2024-06-14 13:51:09,470 WARNING django.server "GET /api/files/ HTTP/1.1" 404 4915
2024-06-14 13:53:35,185 INFO django.utils.autoreload Watching for file changes with StatReloader
2024-06-14 13:53:54,071 WARNING django.request Bad Request: /api/files/
2024-06-14 13:53:54,071 WARNING django.server "POST /api/files/ HTTP/1.1" 400 43
2024-06-14 13:53:54,132 INFO django.server "GET /api/files/ HTTP/1.1" 200 2
2024-06-14 13:55:34,376 INFO django.utils.autoreload C:\Users\maxiw\PycharmProjects\MyCloud_backend\MyCloud\server\routers.py changed, reloading.
2024-06-14 13:55:34,721 INFO django.utils.autoreload Watching for file changes with StatReloader
