2024-06-14 11:31:55,676 INFO django.utils.autoreload Watching for file changes with StatReloader
2024-06-14 11:32:04,158 INFO django.utils.autoreload C:\Users\maxiw\Desktop\netology-cloud-storage-master\storage\viewsets.py changed, reloading.
2024-06-14 11:32:04,462 INFO django.utils.autoreload Watching for file changes with StatReloader
2024-06-14 11:32:09,077 INFO django.utils.autoreload Watching for file changes with StatReloader
2024-06-14 11:32:12,727 WARNING django.request Not Found: /
2024-06-14 11:32:12,728 WARNING django.server "GET / HTTP/1.1" 404 2928
2024-06-14 11:32:12,794 WARNING django.request Not Found: /favicon.ico
2024-06-14 11:32:12,795 WARNING django.server "GET /favicon.ico HTTP/1.1" 404 2979
2024-06-14 11:32:36,750 INFO django.server "POST /login/ HTTP/1.1" 200 149
2024-06-14 11:32:36,788 INFO django.server "GET /api/files/ HTTP/1.1" 200 2
2024-06-14 11:32:36,792 INFO django.server "GET /api/users/6/ HTTP/1.1" 200 118
2024-06-14 11:32:36,796 INFO django.server "GET /api/users/ HTTP/1.1" 200 700
2024-06-14 11:32:36,813 INFO django.server "GET /api/users/6/ HTTP/1.1" 200 118
2024-06-14 11:32:36,822 INFO django.server "GET /api/files/ HTTP/1.1" 200 2
2024-06-14 11:32:36,841 INFO django.server "GET /api/users/ HTTP/1.1" 200 700
2024-06-14 11:33:05,411 INFO django.server "POST /api/files/ HTTP/1.1" 201 261
2024-06-14 11:33:05,443 INFO django.server "GET /api/files/ HTTP/1.1" 200 263
2024-06-14 11:33:26,474 WARNING django.request Bad Request: /api/files/
2024-06-14 11:33:26,474 WARNING django.server "POST /api/files/ HTTP/1.1" 400 41
2024-06-14 11:33:26,503 INFO django.server "GET /api/files/ HTTP/1.1" 200 263
2024-06-14 11:33:33,252 INFO django.server "GET /logout/ HTTP/1.1" 200 79
2024-06-14 11:33:37,578 ERROR django.request Internal Server Error: /login/
Traceback (most recent call last):
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\accounts\views.py", line 48, in login_view
    token = Token.objects.get(user=authenticated_user)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\django\db\models\query.py", line 647, in get
    raise self.model.DoesNotExist(
rest_framework.authtoken.models.Token.DoesNotExist: Token matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.NotNullViolation: null value in column "user_id" of relation "authtoken_token" violates not-null constraint
DETAIL:  Failing row contains (95e732947c08fbe8933b6c69c4ccd4fadf30af60, 2024-06-14 08:33:37.557664+00, null).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\accounts\views.py", line 50, in login_view
    token = Token.objects.create(user=authenticated_user)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\django\db\models\query.py", line 677, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\rest_framework\authtoken\models.py", line 33, in save
    return super().save(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\django\db\models\base.py", line 901, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\django\db\models\base.py", line 1059, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\django\db\models\base.py", line 1100, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\django\db\models\query.py", line 1845, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\maxiw\Desktop\netology-cloud-storage-master\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: null value in column "user_id" of relation "authtoken_token" violates not-null constraint
DETAIL:  Failing row contains (95e732947c08fbe8933b6c69c4ccd4fadf30af60, 2024-06-14 08:33:37.557664+00, null).

2024-06-14 11:33:37,582 ERROR django.server "POST /login/ HTTP/1.1" 500 201939
2024-06-14 11:33:42,677 INFO django.server "POST /register/ HTTP/1.1" 201 135
2024-06-14 11:33:42,695 INFO django.server "OPTIONS /api/users/7/ HTTP/1.1" 200 0
2024-06-14 11:33:42,698 INFO django.server "OPTIONS /api/users/7/ HTTP/1.1" 200 0
2024-06-14 11:33:42,716 INFO django.server "GET /api/files/ HTTP/1.1" 200 2
2024-06-14 11:33:42,720 INFO django.server "GET /api/users/7/ HTTP/1.1" 200 37
2024-06-14 11:33:42,727 INFO django.server "GET /api/users/ HTTP/1.1" 200 39
2024-06-14 11:33:42,743 INFO django.server "GET /api/users/7/ HTTP/1.1" 200 37
2024-06-14 11:33:42,750 INFO django.server "GET /api/users/ HTTP/1.1" 200 39
2024-06-14 11:33:42,757 INFO django.server "GET /api/files/ HTTP/1.1" 200 2
2024-06-14 11:33:54,574 INFO django.server "POST /api/files/ HTTP/1.1" 201 257
2024-06-14 11:33:54,606 INFO django.server "GET /api/files/ HTTP/1.1" 200 259
2024-06-14 11:33:59,035 INFO django.server "OPTIONS /api/files/2/ HTTP/1.1" 200 0
2024-06-14 11:33:59,060 INFO django.server "PATCH /api/files/2/ HTTP/1.1" 200 72
2024-06-14 11:33:59,089 INFO django.server "GET /api/files/ HTTP/1.1" 200 261
2024-06-14 11:34:00,108 INFO django.server "OPTIONS /api/files/2 HTTP/1.1" 200 0
2024-06-14 11:34:00,116 INFO django.server "GET /api/files/2 HTTP/1.1" 301 0
2024-06-14 11:34:00,118 INFO django.server "OPTIONS /api/files/2/ HTTP/1.1" 200 0
2024-06-14 11:34:00,136 INFO django.server "GET /api/files/2/ HTTP/1.1" 200 259
2024-06-14 11:34:00,183 INFO django.server "GET /files/test/weaqea.jpg HTTP/1.1" 200 67866
2024-06-14 11:34:12,469 INFO django.server "GET /s/file-5978263204388066456 HTTP/1.1" 301 0
2024-06-14 11:34:12,488 WARNING django.request Not Found: /s/file-5978263204388066456/
2024-06-14 11:34:12,489 WARNING django.server "GET /s/file-5978263204388066456/ HTTP/1.1" 404 20
2024-06-14 11:34:21,181 WARNING django.request Not Found: /s/file-5978263204388066456/
2024-06-14 11:34:21,181 WARNING django.server "GET /s/file-5978263204388066456/ HTTP/1.1" 404 20
2024-06-14 11:34:43,269 INFO django.server "GET /logout/ HTTP/1.1" 200 67
2024-06-14 11:34:50,398 INFO django.server "POST /login/ HTTP/1.1" 200 149
2024-06-14 11:34:50,445 INFO django.server "GET /api/users/6/ HTTP/1.1" 200 128
2024-06-14 11:34:50,445 INFO django.server "GET /api/files/ HTTP/1.1" 200 523
2024-06-14 11:34:50,449 INFO django.server "GET /api/users/ HTTP/1.1" 200 836
2024-06-14 11:34:50,472 INFO django.server "GET /api/files/ HTTP/1.1" 200 523
2024-06-14 11:34:50,473 INFO django.server "GET /api/users/6/ HTTP/1.1" 200 128
2024-06-14 11:34:50,481 INFO django.server "GET /api/users/ HTTP/1.1" 200 836
2024-06-14 11:34:52,586 INFO django.server "GET /api/users/6/ HTTP/1.1" 200 128
2024-06-14 11:34:52,605 INFO django.server "GET /api/users/6/ HTTP/1.1" 200 128
2024-06-14 11:34:52,627 INFO django.server "GET /api/users/6/ HTTP/1.1" 200 128
2024-06-14 11:34:52,646 INFO django.server "GET /api/users/6/ HTTP/1.1" 200 128
2024-06-14 11:34:52,655 INFO django.server "GET /api/users/ HTTP/1.1" 200 836
2024-06-14 11:34:52,677 INFO django.server "GET /api/users/ HTTP/1.1" 200 836
2024-06-14 11:34:54,635 INFO django.server "DELETE /api/users/2/ HTTP/1.1" 204 54
2024-06-14 11:34:54,640 INFO django.server - Broken pipe from ('127.0.0.1', 58871)
2024-06-14 11:34:54,656 INFO django.server "GET /api/users/ HTTP/1.1" 200 720
2024-06-14 11:34:56,198 INFO django.server "DELETE /api/users/3/ HTTP/1.1" 204 53
2024-06-14 11:34:56,200 INFO django.server - Broken pipe from ('127.0.0.1', 58842)
2024-06-14 11:34:56,220 INFO django.server "GET /api/users/ HTTP/1.1" 200 605
2024-06-14 11:34:57,372 INFO django.server "DELETE /api/users/4/ HTTP/1.1" 204 58
2024-06-14 11:34:57,375 INFO django.server - Broken pipe from ('127.0.0.1', 58932)
2024-06-14 11:34:57,392 INFO django.server "GET /api/users/ HTTP/1.1" 200 485
2024-06-14 11:34:58,546 INFO django.server "DELETE /api/users/5/ HTTP/1.1" 204 54
2024-06-14 11:34:58,548 INFO django.server - Broken pipe from ('127.0.0.1', 58935)
2024-06-14 11:34:58,568 INFO django.server "GET /api/users/ HTTP/1.1" 200 369
2024-06-14 11:35:00,783 INFO django.server "PATCH /api/users/7/ HTTP/1.1" 200 52
2024-06-14 11:35:00,808 INFO django.server "GET /api/users/ HTTP/1.1" 200 368
2024-06-14 11:35:02,192 INFO django.server "DELETE /api/users/7/ HTTP/1.1" 204 52
2024-06-14 11:35:02,194 INFO django.server - Broken pipe from ('127.0.0.1', 58940)
2024-06-14 11:35:02,213 INFO django.server "GET /api/users/ HTTP/1.1" 200 243
2024-06-14 11:45:03,043 INFO django.utils.autoreload Watching for file changes with StatReloader
